public enum StreamChatType
{
    DESTROY_BUILDING,
    KILL_CIVILIAN,
    KILl_HOSTILES,
    ADD_SEGMENTS,
    SNAKE_BUFF,
    WANTED_LEVEL,
    SUBSCRIBE_TRESHOLD,
    BOSS_FIGHT,
    MISSION_COMPLETE,
    TAKE_DAMAGE,
    RANDOM_CHAT,
}
